(() => {
  const s={result:null,turn:0,timer:null};
  const q=(id)=>document.querySelector(id);
  const slider=q("#turn-slider"),reset=q("#reset-button"),prev=q("#previous-button"),play=q("#play-button"),next=q("#next-button"),speed=q("#speed-select"),workspace=q("#simulation-workspace");
  function stop(){if(s.timer!==null){clearInterval(s.timer);s.timer=null}play.textContent="▶";play.setAttribute("aria-label","Play simulation")}
  function render(turn){if(!s.result)return;s.turn=Math.max(0,Math.min(turn,s.result.turn_count));slider.value=String(s.turn);prev.disabled=s.turn===0;reset.disabled=s.turn===0;next.disabled=s.turn>=s.result.turn_count;window.renderFlyInTurn(s.result,s.turn)}
  function load(result,map){stop();s.result=result;s.turn=0;q("#workspace-map-name").textContent=`#${map.index} · ${map.display_path}`;q("#metric-turns").textContent=String(result.turn_count);q("#metric-drones").textContent=String(result.map.drone_count);q("#metric-cost").textContent=String(result.metrics.total_path_cost);q("#metric-average").textContent=result.metrics.average_turns_per_drone.toFixed(1);slider.min="0";slider.max=String(result.turn_count);slider.value="0";slider.disabled=false;speed.disabled=false;play.disabled=result.turn_count===0;next.disabled=result.turn_count===0;window.renderFlyInOutput(result);render(0);workspace.classList.remove("is-hidden");workspace.scrollIntoView({behavior:"smooth",block:"start"})}
  function clear(){stop();s.result=null;s.turn=0;workspace.classList.add("is-hidden");window.FlyInGraph.resetInspector();window.uiLog?.("simulation:cleared")}
  function toggle(){if(!s.result)return;if(s.timer!==null){stop();window.uiLog?.("playback:pause",{turn:s.turn});return}if(s.turn>=s.result.turn_count)render(0);const delay=Number(speed.value);play.textContent="Ⅱ";play.setAttribute("aria-label","Pause simulation");s.timer=setInterval(()=>{if(s.turn>=s.result.turn_count){stop();window.uiLog?.("playback:complete",{turn:s.turn});return}render(s.turn+1)},delay);window.uiLog?.("playback:play",{turn:s.turn,delay_ms:delay})}
  reset.addEventListener("click",()=>{stop();render(0);window.uiLog?.("playback:reset")});prev.addEventListener("click",()=>{stop();render(s.turn-1);window.uiLog?.("playback:previous",{turn:s.turn})});next.addEventListener("click",()=>{stop();render(s.turn+1);window.uiLog?.("playback:next",{turn:s.turn})});play.addEventListener("click",toggle);slider.addEventListener("input",()=>{stop();render(Number(slider.value));window.uiLog?.("playback:seek",{turn:s.turn})});speed.addEventListener("change",()=>{const running=s.timer!==null;stop();if(running)toggle();window.uiLog?.("playback:speed-change",{delay_ms:Number(speed.value)})});
  window.FlyInSimulation={load,clear};
})();
